// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package protoc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MSG_TYPE int32

const (
	MSG_TYPE_MSG_MOVE MSG_TYPE = 0
)

var MSG_TYPE_name = map[int32]string{
	0: "MSG_MOVE",
}
var MSG_TYPE_value = map[string]int32{
	"MSG_MOVE": 0,
}

func (x MSG_TYPE) String() string {
	return proto.EnumName(MSG_TYPE_name, int32(x))
}
func (MSG_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_48bac0891cd58522, []int{0}
}

type Pos struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pos) Reset()         { *m = Pos{} }
func (m *Pos) String() string { return proto.CompactTextString(m) }
func (*Pos) ProtoMessage()    {}
func (*Pos) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_48bac0891cd58522, []int{0}
}
func (m *Pos) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pos.Unmarshal(m, b)
}
func (m *Pos) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pos.Marshal(b, m, deterministic)
}
func (dst *Pos) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pos.Merge(dst, src)
}
func (m *Pos) XXX_Size() int {
	return xxx_messageInfo_Pos.Size(m)
}
func (m *Pos) XXX_DiscardUnknown() {
	xxx_messageInfo_Pos.DiscardUnknown(m)
}

var xxx_messageInfo_Pos proto.InternalMessageInfo

func (m *Pos) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Pos) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type C2SPlayerMove struct {
	Msg                  MSG_TYPE `protobuf:"varint,1,opt,name=msg,proto3,enum=protoc.MSG_TYPE" json:"msg,omitempty"`
	PlayerId             int32    `protobuf:"varint,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Pos                  *Pos     `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SPlayerMove) Reset()         { *m = C2SPlayerMove{} }
func (m *C2SPlayerMove) String() string { return proto.CompactTextString(m) }
func (*C2SPlayerMove) ProtoMessage()    {}
func (*C2SPlayerMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_48bac0891cd58522, []int{1}
}
func (m *C2SPlayerMove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SPlayerMove.Unmarshal(m, b)
}
func (m *C2SPlayerMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SPlayerMove.Marshal(b, m, deterministic)
}
func (dst *C2SPlayerMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SPlayerMove.Merge(dst, src)
}
func (m *C2SPlayerMove) XXX_Size() int {
	return xxx_messageInfo_C2SPlayerMove.Size(m)
}
func (m *C2SPlayerMove) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SPlayerMove.DiscardUnknown(m)
}

var xxx_messageInfo_C2SPlayerMove proto.InternalMessageInfo

func (m *C2SPlayerMove) GetMsg() MSG_TYPE {
	if m != nil {
		return m.Msg
	}
	return MSG_TYPE_MSG_MOVE
}

func (m *C2SPlayerMove) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *C2SPlayerMove) GetPos() *Pos {
	if m != nil {
		return m.Pos
	}
	return nil
}

func init() {
	proto.RegisterType((*Pos)(nil), "protoc.Pos")
	proto.RegisterType((*C2SPlayerMove)(nil), "protoc.C2SPlayerMove")
	proto.RegisterEnum("protoc.MSG_TYPE", MSG_TYPE_name, MSG_TYPE_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_common_48bac0891cd58522) }

var fileDescriptor_common_48bac0891cd58522 = []byte{
	// 171 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc9, 0x4a, 0x8a, 0x5c,
	0xcc, 0x01, 0xf9, 0xc5, 0x42, 0x3c, 0x5c, 0x8c, 0x15, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41,
	0x8c, 0x15, 0x20, 0x5e, 0xa5, 0x04, 0x13, 0x84, 0x57, 0xa9, 0x94, 0xc7, 0xc5, 0xeb, 0x6c, 0x14,
	0x1c, 0x90, 0x93, 0x58, 0x99, 0x5a, 0xe4, 0x9b, 0x5f, 0x96, 0x2a, 0xa4, 0xc4, 0xc5, 0x9c, 0x5b,
	0x9c, 0x0e, 0x56, 0xce, 0x67, 0x24, 0x00, 0x31, 0x30, 0x59, 0xcf, 0x37, 0xd8, 0x3d, 0x3e, 0x24,
	0x32, 0xc0, 0x35, 0x08, 0x24, 0x29, 0x24, 0xc5, 0xc5, 0x51, 0x00, 0xd6, 0xe1, 0x99, 0x02, 0x35,
	0x09, 0xce, 0x17, 0x92, 0xe5, 0x62, 0x2e, 0xc8, 0x2f, 0x96, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x36,
	0xe2, 0x86, 0xe9, 0x0f, 0xc8, 0x2f, 0x0e, 0x02, 0x89, 0x6b, 0x49, 0x70, 0x71, 0xc0, 0xcc, 0x12,
	0xe2, 0x81, 0xb0, 0x7d, 0xfd, 0xc3, 0x5c, 0x05, 0x18, 0x92, 0x20, 0x8e, 0x36, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xf2, 0xbe, 0x00, 0x87, 0xcb, 0x00, 0x00, 0x00,
}
